<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-NOB8PMF" failures="0" tests="7" name="Test.TestNG" time="1.070" errors="1" timestamp="2022-06-02T20:51:38 IST" skipped="2">
  <testcase classname="Test.TestNG" name="test2" time="0.014"/>
  <system-out/>
  <testcase classname="Test.TestNG" name="test2" time="0.004"/>
  <system-out/>
  <testcase classname="Test.TestNG" name="test2" time="0.015"/>
  <system-out/>
  <testcase classname="Test.TestNG" name="test3" time="0.005"/>
  <system-out/>
  <testcase classname="Test.TestNG" name="test5" time="0.000">
    <skipped/>
  </testcase> <!-- test5 -->
  <system-out/>
  <testcase classname="Test.TestNG" name="test1" time="1.032">
    <error message="Method Test.TestNG.test1() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method Test.TestNG.test1() didn't finish within the time-out 1000
at java.base@18.0.1/java.lang.Thread.sleep(Native Method)
at app//Test.TestNG.test1(TestNG.java:17)
at java.base@18.0.1/java.lang.invoke.LambdaForm$DMH/0x0000000100180000.invokeVirtual(LambdaForm$DMH)
at java.base@18.0.1/java.lang.invoke.LambdaForm$MH/0x0000000100180800.invoke(LambdaForm$MH)
at java.base@18.0.1/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
at java.base@18.0.1/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:154)
at java.base@18.0.1/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base@18.0.1/java.lang.reflect.Method.invoke(Method.java:577)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:44)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:72)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:10)
at java.base@18.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@18.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@18.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@18.0.1/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="Test.TestNG" name="test4">
    <skipped/>
  </testcase> <!-- test4 -->
  <system-out/>
</testsuite> <!-- Test.TestNG -->
